#!/bin/sh
echo "Compiling..."
GOOS=linux go build -a --ldflags '-extldflags "-static"' -tags netgo -installsuffix netgo .

echo "Build container..."
docker build -t dbwp .

echo " "
echo "Running container..."
docker run --rm dbwp
